
package client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "LibraryServerMainService", targetNamespace = "lib", wsdlLocation = "http://localhost:7777/lib?wsdl")
public class LibraryServerMainService
    extends Service
{

    private final static URL LIBRARYSERVERMAINSERVICE_WSDL_LOCATION;
    private final static WebServiceException LIBRARYSERVERMAINSERVICE_EXCEPTION;
    private final static QName LIBRARYSERVERMAINSERVICE_QNAME = new QName("lib", "LibraryServerMainService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:7777/lib?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        LIBRARYSERVERMAINSERVICE_WSDL_LOCATION = url;
        LIBRARYSERVERMAINSERVICE_EXCEPTION = e;
    }

    public LibraryServerMainService() {
        super(__getWsdlLocation(), LIBRARYSERVERMAINSERVICE_QNAME);
    }

    public LibraryServerMainService(WebServiceFeature... features) {
        super(__getWsdlLocation(), LIBRARYSERVERMAINSERVICE_QNAME, features);
    }

    public LibraryServerMainService(URL wsdlLocation) {
        super(wsdlLocation, LIBRARYSERVERMAINSERVICE_QNAME);
    }

    public LibraryServerMainService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, LIBRARYSERVERMAINSERVICE_QNAME, features);
    }

    public LibraryServerMainService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public LibraryServerMainService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns LibraryServerMain
     */
    @WebEndpoint(name = "LibraryServerMainPort")
    public LibraryServerMain getLibraryServerMainPort() {
        return super.getPort(new QName("lib", "LibraryServerMainPort"), LibraryServerMain.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns LibraryServerMain
     */
    @WebEndpoint(name = "LibraryServerMainPort")
    public LibraryServerMain getLibraryServerMainPort(WebServiceFeature... features) {
        return super.getPort(new QName("lib", "LibraryServerMainPort"), LibraryServerMain.class, features);
    }

    private static URL __getWsdlLocation() {
        if (LIBRARYSERVERMAINSERVICE_EXCEPTION!= null) {
            throw LIBRARYSERVERMAINSERVICE_EXCEPTION;
        }
        return LIBRARYSERVERMAINSERVICE_WSDL_LOCATION;
    }

}
