
package com.concordia.comp6231.client.uqam;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "drmsService", targetNamespace = "http://com.concordia", wsdlLocation = "http://localhost:7779/drms?wsdl")
public class DrmsService
    extends Service
{

    private final static URL DRMSSERVICE_WSDL_LOCATION;
    private final static WebServiceException DRMSSERVICE_EXCEPTION;
    private final static QName DRMSSERVICE_QNAME = new QName("http://com.concordia", "drmsService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:7779/drms?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        DRMSSERVICE_WSDL_LOCATION = url;
        DRMSSERVICE_EXCEPTION = e;
    }

    public DrmsService() {
        super(__getWsdlLocation(), DRMSSERVICE_QNAME);
    }

    public DrmsService(WebServiceFeature... features) {
        super(__getWsdlLocation(), DRMSSERVICE_QNAME, features);
    }

    public DrmsService(URL wsdlLocation) {
        super(wsdlLocation, DRMSSERVICE_QNAME);
    }

    public DrmsService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, DRMSSERVICE_QNAME, features);
    }

    public DrmsService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DrmsService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Drms
     */
    @WebEndpoint(name = "drmsPort")
    public Drms getDrmsPort() {
        return super.getPort(new QName("http://com.concordia", "drmsPort"), Drms.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Drms
     */
    @WebEndpoint(name = "drmsPort")
    public Drms getDrmsPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://com.concordia", "drmsPort"), Drms.class, features);
    }

    private static URL __getWsdlLocation() {
        if (DRMSSERVICE_EXCEPTION!= null) {
            throw DRMSSERVICE_EXCEPTION;
        }
        return DRMSSERVICE_WSDL_LOCATION;
    }

}
