
package com.concordia.comp6231.client.mcgill;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Drms", targetNamespace = "http://comp6231.concordia.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Drms {


    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "reserveInterLibrary", targetNamespace = "http://comp6231.concordia.com/", className = "com.concordia.comp6231.client.mcgill.ReserveInterLibrary")
    @ResponseWrapper(localName = "reserveInterLibraryResponse", targetNamespace = "http://comp6231.concordia.com/", className = "com.concordia.comp6231.client.mcgill.ReserveInterLibraryResponse")
    @Action(input = "http://comp6231.concordia.com/Drms/reserveInterLibraryRequest", output = "http://comp6231.concordia.com/Drms/reserveInterLibraryResponse")
    public String reserveInterLibrary(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3);

    /**
     * 
     * @param arg5
     * @param arg4
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @param arg6
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "createAccount", targetNamespace = "http://comp6231.concordia.com/", className = "com.concordia.comp6231.client.mcgill.CreateAccount")
    @ResponseWrapper(localName = "createAccountResponse", targetNamespace = "http://comp6231.concordia.com/", className = "com.concordia.comp6231.client.mcgill.CreateAccountResponse")
    @Action(input = "http://comp6231.concordia.com/Drms/createAccountRequest", output = "http://comp6231.concordia.com/Drms/createAccountResponse")
    public String createAccount(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        long arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        String arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        String arg5,
        @WebParam(name = "arg6", targetNamespace = "")
        String arg6);

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "reserveBook", targetNamespace = "http://comp6231.concordia.com/", className = "com.concordia.comp6231.client.mcgill.ReserveBook")
    @ResponseWrapper(localName = "reserveBookResponse", targetNamespace = "http://comp6231.concordia.com/", className = "com.concordia.comp6231.client.mcgill.ReserveBookResponse")
    @Action(input = "http://comp6231.concordia.com/Drms/reserveBookRequest", output = "http://comp6231.concordia.com/Drms/reserveBookResponse")
    public String reserveBook(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "setDuration", targetNamespace = "http://comp6231.concordia.com/", className = "com.concordia.comp6231.client.mcgill.SetDuration")
    @ResponseWrapper(localName = "setDurationResponse", targetNamespace = "http://comp6231.concordia.com/", className = "com.concordia.comp6231.client.mcgill.SetDurationResponse")
    @Action(input = "http://comp6231.concordia.com/Drms/setDurationRequest", output = "http://comp6231.concordia.com/Drms/setDurationResponse")
    public String setDuration(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        int arg2);

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getNonReturners", targetNamespace = "http://comp6231.concordia.com/", className = "com.concordia.comp6231.client.mcgill.GetNonReturners")
    @ResponseWrapper(localName = "getNonReturnersResponse", targetNamespace = "http://comp6231.concordia.com/", className = "com.concordia.comp6231.client.mcgill.GetNonReturnersResponse")
    @Action(input = "http://comp6231.concordia.com/Drms/getNonReturnersRequest", output = "http://comp6231.concordia.com/Drms/getNonReturnersResponse")
    public String getNonReturners(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        int arg3);

}
